### PR TITLE
Add detailed dashboard

### LINKED ISSUE #179: Detailed Dashboard
# Problem

Besides a summary side panel, we also need a detailed dashboard to interrogate the data in more detail.

The detailed dashboard needs to pull information from the base module as well as all the other modules.

# Proposed Solution

Develop a detailed dashboard which pulls all details as specified for the Fish Module from the current filtered site/sites data.

### PR DESCRIPTION
**Pull request by ann26**
fix #179 

peek 2018-09-19 05-14

Fish graph and table are rendered from https://github.com/kartoza/kbims-fish/pull/8

### CODE REVIEW

**Comment by meomancer** [comment]
hi @ann26 
good job

hi @cchristelis @ann26 
i'm not sure for the layout
1. side panel overlaps the navbar, maybe give margin top to fit it just on map?
2. the full screen when see "detailed dashboard" is bland and not fit with healthirivers theme, maybe is there any layout for this @carina1000 ?
3. I see there is "chain" logo. is the purpose to copy the link of detailde dashboard? if yes, is it make sense to show it in new page? and redirect "detailed dashboard" into that page? I think it will not hard, because of just calls detail of site.

**Comment by ann26** [comment]
hi @meomancer 

> 4. On the detailed dashboard, there is just "fish section". will it show for other module too?

yes


> 5. Also add legend on pie chart. I don't know what the representation of colors in chart.

we can hover on the pie chart, I think we don't need legend for this


> 6. The bar chart is like timeline (x is time). it is better to use line chart.

yeah that's probably good too, I made it using bar graph because it was based on the mockup below
screenshot from 2018-09-19 06-15-49

**Comment by ann26** [comment]
@meomancer 
1. Margin is added
7. Title is added

peek 2018-09-19 06-37

**Comment by meomancer** [comment]
hi @ann26 
> we can hover on the pie chart, I think we don't need legend for this

will this dashboard able to downloaded (like into jpeg, or pdf)? If yes, i think we need legend, if no, ignore this

**Comment by ann26** [comment]
@meomancer I think the page that is going to be downloaded as jpg or pdf will be different (not this one)

**Pull request merged**
