### PR TITLE
Schema migrations 

### LINKED ISSUE #60: Database schema migration
# Problem 

The old database was over normalized, which lead to complexity in both uploading and managing the data. Secondly it lead to many unused features and a lot of missing data.

# Proposed Solution 

Do a schema migration according to the plan set out in this document: https://docs.google.com/document/d/18xQvIipQO4IyeV2Ik6uBtagsY-0SADlSWpNZyjkqwj0/edit?usp=sharing

### PR DESCRIPTION
**Pull request by sonlinux**
See #60, supercedes #73

Database schema migrations as per recomendation document

### CODE REVIEW

**Comment by timlinux** [comment]
That is looking much better @sonlinux ! I will test it here.

**Comment by timlinux** [comment]
When I tried to run your script I got this:

```
[2018-02-13 11:59:55] Run /Users/timlinux/Library/Preferences/DataGrip2017.1/scratches/scratch.sql
[2018-02-13 11:59:55] Connecting to HealthRivers...
[2018-02-13 11:59:55] Using batch mode (1000 insert/update/delete statements max)
ALTER TABLE site DROP COLUMN oldsitecode
[2018-02-13 11:59:56] 0 row(s) affected in 20ms
ALTER TABLE site DROP COLUMN projectsitenumber
[2018-02-13 11:59:56] 0 row(s) affected in 2ms
ALTER TABLE site DROP COLUMN longitudinalzoneid
[2018-02-13 11:59:56] [42703] ERROR: column "longitudinalzoneid" of relation "site" does not exist
ALTER TABLE site DROP COLUMN reference
[2018-02-13 11:59:56] 0 row(s) affected in 2ms
ALTER TABLE site DROP COLUMN mapreference
[2018-02-13 11:59:56] 0 row(s) affected in 1ms
ALTER TABLE site DROP COLUMN contrangefrom
[2018-02-13 11:59:56] 0 row(s) affected in 1ms
ALTER TABLE site DROP COLUMN contrangeto
[2018-02-13 11:59:56] 0 row(s) affected in 1ms
ALTER TABLE site DROP COLUMN sitelength
[2018-02-13 11:59:56] 0 row(s) affected in 1ms
ALTER TABLE site DROP COLUMN "Source"
[2018-02-13 11:59:56] 0 row(s) affected in 1ms
ALTER TABLE site DROP COLUMN hydrotypeid
[2018-02-13 11:59:56] 0 row(s) affected in 3ms
ALTER TABLE site DROP COLUMN hydrotypenaturalid
[2018-02-13 11:59:56] 0 row(s) affected in 2ms
ALTER TABLE site DROP COLUMN gaugingstation
[2018-02-13 11:59:56] 0 row(s) affected in 2ms
ALTER TABLE site DROP COLUMN dwafcode
[2018-02-13 11:59:56] 0 row(s) affected in 2ms
ALTER TABLE site DROP COLUMN distup
[2018-02-13 11:59:56] 0 row(s) affected in 2ms
ALTER TABLE site DROP COLUMN distdown
[2018-02-13 11:59:56] 0 row(s) affected in 2ms
ALTER TABLE site DROP COLUMN assossysid
[2018-02-13 11:59:56] [42703] ERROR: column "assossysid" of relation "site" does not exist
ALTER TABLE site DROP COLUMN assocsysdist
[2018-02-13 11:59:56] 0 row(s) affected in 2ms
ALTER TABLE site DROP COLUMN assocsysname
[2018-02-13 11:59:56] 0 row(s) affected in 4ms
ALTER TABLE site DROP COLUMN "Notify"
[2018-02-13 11:59:56] 0 row(s) affected in 2ms
ALTER TABLE site DROP COLUMN permitrequired
[2018-02-13 11:59:56] 0 row(s) affected in 1ms
ALTER TABLE site DROP COLUMN permitdetails
[2018-02-13 11:59:56] 0 row(s) affected in 1ms
ALTER TABLE site DROP COLUMN permitacquired
[2018-02-13 11:59:56] 0 row(s) affected in 1ms
ALTER TABLE site DROP COLUMN validityofpermit
[2018-02-13 11:59:56] 0 row(s) affected in 1ms
ALTER TABLE site DROP COLUMN "Key"
[2018-02-13 11:59:56] 0 row(s) affected in 1ms
ALTER TABLE site DROP COLUMN keyavailability
[2018-02-13 11:59:56] 0 row(s) affected in 1ms
ALTER TABLE site DROP COLUMN farm
[2018-02-13 11:59:56] 0 row(s) affected in 2ms
ALTER TABLE site DROP COLUMN farmregistrationcode
[2018-02-13 11:59:56] 0 row(s) affected in 2ms
ALTER TABLE site DROP COLUMN georeferencecomment
[2018-02-13 11:59:56] 0 row(s) affected in 1ms
ALTER TABLE site DROP COLUMN mapprojection
[2018-02-13 11:59:56] 0 row(s) affected in 1ms
ALTER TABLE sitevisit DROP COLUMN "Time"
[2018-02-13 11:59:56] [42703] ERROR: column "Time" of relation "sitevisit" does not exist
ALTER TABLE sitevisit DROP COLUMN rain
[2018-02-13 11:59:56] [42703] ERROR: column "rain" of relation "sitevisit" does not exist
ALTER TABLE sitevisit DROP COLUMN raincomment
[2018-02-13 11:59:56] [42703] ERROR: column "raincomment" of relation "sitevisit" does not exist
ALTER TABLE sitevisit DROP COLUMN embeddednessid
[2018-02-13 11:59:56] [42703] ERROR: column "embeddednessid" of relation "sitevisit" does not exist
ALTER TABLE sitevisit DROP COLUMN fastflow
[2018-02-13 11:59:56] [42703] ERROR: column "fastflow" of relation "sitevisit" does not exist
ALTER TABLE sitevisit DROP COLUMN fastflowname
[2018-02-13 11:59:56] [42703] ERROR: column "fastflowname" of relation "sitevisit" does not exist
ALTER TABLE sitevisit DROP COLUMN waterfiltered
[2018-02-13 11:59:56] [42703] ERROR: column "waterfiltered" of relation "sitevisit" does not exist
ALTER TABLE sitevisit DROP COLUMN volfiltered
[2018-02-13 11:59:56] [42703] ERROR: column "volfiltered" of relation "sitevisit" does not exist
ALTER TABLE sitevisit DROP COLUMN samples
[2018-02-13 11:59:56] [42703] ERROR: column "samples" of relation "sitevisit" does not exist
ALTER TABLE sitevisit DROP COLUMN analysis
[2018-02-13 11:59:56] [42703] ERROR: column "analysis" of relation "sitevisit" does not exist
ALTER TABLE sitevisit DROP COLUMN frozen
[2018-02-13 11:59:56] [42703] ERROR: column "frozen" of relation "sitevisit" does not exist
ALTER TABLE sitevisit DROP COLUMN prev
[2018-02-13 11:59:56] [42703] ERROR: column "prev" of relation "sitevisit" does not exist
ALTER TABLE sitevisit DROP COLUMN sampleinstitute
[2018-02-13 11:59:56] [42703] ERROR: column "sampleinstitute" of relation "sitevisit" does not exist
ALTER TABLE sitevisit DROP COLUMN canopycovercomment
[2018-02-13 11:59:56] [42703] ERROR: column "canopycovercomment" of relation "sitevisit" does not exist
ALTER TABLE sitevisit DROP COLUMN habitatintegritycomment
[2018-02-13 11:59:56] [42703] ERROR: column "habitatintegritycomment" of relation "sitevisit" does not exist
ALTER TABLE sitevisit DROP COLUMN sassdatacomment
[2018-02-13 11:59:56] [42703] ERROR: column "sassdatacomment" of relation "sitevisit" does not exist
ALTER TABLE sitevisit DROP COLUMN fishowner
[2018-02-13 11:59:56] [42703] ERROR: column "fishowner" of relation "sitevisit" does not exist
ALTER TABLE sitevisit DROP COLUMN fishassessor
[2018-02-13 11:59:56] [42703] ERROR: column "fishassessor" of relation "sitevisit" does not exist
ALTER TABLE sitevisit DROP COLUMN ripirianowner
[2018-02-13 11:59:56] [42703] ERROR: column "ripirianowner" of relation "sitevisit" does not exist
ALTER TABLE sitevisit DROP COLUMN ripirianassessor
[2018-02-13 11:59:56] [42703] ERROR: column "ripirianassessor" of relation "sitevisit" does not exist
ALTER TABLE sitevisit DROP COLUMN waterchemistryowner
[2018-02-13 11:59:56] [42703] ERROR: column "waterchemistryowner" of relation "sitevisit" does not exist
ALTER TABLE sitevisit DROP COLUMN waterchemistryassessor
[2018-02-13 11:59:56] [42703] ERROR: column "waterchemistryassessor" of relation "sitevisit" does not exist
ALTER TABLE sitevisit DROP COLUMN channeltypeid
[2018-02-13 11:59:56] [42703] ERROR: column "channeltypeid" of relation "sitevisit" does not exist
DROP TABLE archived_channeldescription
[2018-02-13 11:59:56] 0 row(s) affected in 24ms
DROP TABLE archived_chemistry_generalinformation
[2018-02-13 11:59:56] 0 row(s) affected in 6ms
DROP TABLE archived_geomorphology
[2018-02-13 11:59:56] 0 row(s) affected in 7ms
DROP TABLE archived_habitatassessmentham_hqi
[2018-02-13 11:59:56] 0 row(s) affected in 6ms
DROP TABLE archived_indexofhabitatintegrity
[2018-02-13 11:59:56] 0 row(s) affected in 4ms
DROP TABLE archived_riparianvegetationindex
[2018-02-13 11:59:56] 0 row(s) affected in 5ms
DROP TABLE archived_riparianzonedescription
[2018-02-13 11:59:56] 0 row(s) affected in 3ms
DROP TABLE archived_sitecondition
[2018-02-13 11:59:56] 0 row(s) affected in 4ms
DROP TABLE archived_speciesrichness
[2018-02-13 11:59:56] 0 row(s) affected in 2ms
DROP TABLE archived_vegetationcover
[2018-02-13 11:59:56] 0 row(s) affected in 4ms
DROP TABLE archived_vegetationdistribution
[2018-02-13 11:59:56] 0 row(s) affected in 5ms
DROP TABLE archived_vegetationinvasion
[2018-02-13 11:59:56] 0 row(s) affected in 4ms
DROP TABLE archived_vegetationspecieslist
[2018-02-13 11:59:56] 0 row(s) affected in 3ms
DROP TABLE temp_view_archived_chemistry_generalinformation
[2018-02-13 11:59:56] 0 row(s) affected in 4ms
DROP TABLE temp_view_archived_riparianvegetationindex
[2018-02-13 11:59:56] 0 row(s) affected in 3ms
DROP TABLE temp_view_archiveddata
[2018-02-13 11:59:56] 0 row(s) affected in 2ms
DROP TABLE temp_view_indexofhabitatintegrity
[2018-02-13 11:59:56] 0 row(s) affected in 1ms
DROP TABLE temp_view_sitegeomorphology
[2018-02-13 11:59:56] [42P01] ERROR: table "temp_view_sitegeomorphology" does not exist
DROP TABLE temp_view_sitegeoreference
[2018-02-13 11:59:56] [42P01] ERROR: table "temp_view_sitegeoreference" does not exist
DROP TABLE temp_view_siteinformationgeneral
[2018-02-13 11:59:56] [42P01] ERROR: table "temp_view_siteinformationgeneral" does not exist
DROP TABLE temp_view_siteinformationlocation
[2018-02-13 11:59:56] [42P01] ERROR: table "temp_view_siteinformationlocation" does not exist
DROP TABLE temp_view_siteinformationregional
[2018-02-13 11:59:56] [42P01] ERROR: table "temp_view_siteinformationregional" does not exist
DROP TABLE temp_view_sitevisitbiotopeinvertebrates
[2018-02-13 11:59:56] [42P01] ERROR: table "temp_view_sitevisitbiotopeinvertebrates" does not exist
DROP TABLE temp_view_sitevisitbiotopeinvertebratesxtababundance
[2018-02-13 11:59:56] 0 row(s) affected in 4ms
DROP TABLE temp_view_sitevisitbiotopeinvertebratesxtababundancesass4
[2018-02-13 11:59:56] 0 row(s) affected in 3ms
DROP TABLE temp_view_sitevisitbiotopeinvertebratesxtababundancesass5
[2018-02-13 11:59:56] 0 row(s) affected in 7ms
DROP TABLE temp_view_sitevisitbiotopeinvertebratesxtabscore
[2018-02-13 11:59:56] 0 row(s) affected in 2ms
DROP TABLE temp_view_sitevisitbiotopeinvertebratesxtabscoresass4
[2018-02-13 11:59:56] 0 row(s) affected in 2ms
DROP TABLE temp_view_sitevisitbiotopeinvertebratesxtabscoresass5
[2018-02-13 11:59:56] 0 row(s) affected in 2ms
DROP TABLE temp_view_sitevisitbiotopes
[2018-02-13 11:59:56] [42P01] ERROR: table "temp_view_sitevisitbiotopes" does not exist
DROP TABLE temp_view_sitevisitbiotopesass_scores
[2018-02-13 11:59:56] [42P01] ERROR: table "temp_view_sitevisitbiotopesass_scores" does not exist
DROP TABLE temp_view_sitevisitchannelmodifications
[2018-02-13 11:59:56] [42P01] ERROR: table "temp_view_sitevisitchannelmodifications" does not exist
DROP TABLE temp_view_sitevisitchannelmorphology
[2018-02-13 11:59:56] [42P01] ERROR: table "temp_view_sitevisitchannelmorphology" does not exist
DROP TABLE temp_view_sitevisitchemistry
[2018-02-13 11:59:56] [42P01] ERROR: table "temp_view_sitevisitchemistry" does not exist
DROP TABLE temp_view_sitevisitchemistrygeneralinformation
[2018-02-13 11:59:56] [42P01] ERROR: table "temp_view_sitevisitchemistrygeneralinformation" does not exist
DROP TABLE temp_view_sitevisitchemistryxtab
[2018-02-13 11:59:56] [42P01] ERROR: table "temp_view_sitevisitchemistryxtab" does not exist
DROP TABLE temp_view_sitevisitfishdatahabitatcover
[2018-02-13 11:59:56] [42P01] ERROR: table "temp_view_sitevisitfishdatahabitatcover" does not exist
DROP TABLE temp_view_sitevisitfishsampledetail
[2018-02-13 11:59:56] [42P01] ERROR: table "temp_view_sitevisitfishsampledetail" does not exist
DROP TABLE temp_view_sitevisitgeomorphology
[2018-02-13 11:59:56] [42P01] ERROR: table "temp_view_sitevisitgeomorphology" does not exist
DROP TABLE temp_view_sitevisitgeoreference
[2018-02-13 11:59:56] [42P01] ERROR: table "temp_view_sitevisitgeoreference" does not exist
DROP TABLE temp_view_sitevisithabitatassessment
[2018-02-13 11:59:56] [42P01] ERROR: table "temp_view_sitevisithabitatassessment" does not exist
DROP TABLE temp_view_sitevisitihas
[2018-02-13 11:59:56] [42P01] ERROR: table "temp_view_sitevisitihas" does not exist
DROP TABLE temp_view_sitevisitinformationgeneral
[2018-02-13 11:59:56] [42P01] ERROR: table "temp_view_sitevisitinformationgeneral" does not exist
DROP TABLE temp_view_sitevisitinformationlocation
[2018-02-13 11:59:56] [42P01] ERROR: table "temp_view_sitevisitinformationlocation" does not exist
DROP TABLE temp_view_sitevisitinformationregional
[2018-02-13 11:59:56] [42P01] ERROR: table "temp_view_sitevisitinformationregional" does not exist
DROP TABLE temp_view_sitevisitinvertebrates
[2018-02-13 11:59:56] [42P01] ERROR: table "temp_view_sitevisitinvertebrates" does not exist
DROP TABLE temp_view_sitevisitlanduse
[2018-02-13 11:59:56] [42P01] ERROR: table "temp_view_sitevisitlanduse" does not exist
DROP TABLE temp_view_sitevisitsamplingoccasiongeneralinformation
[2018-02-13 11:59:56] [42P01] ERROR: table "temp_view_sitevisitsamplingoccasiongeneralinformation" does not exist
DROP TABLE temp_view_sitevisitsass_scores
[2018-02-13 11:59:56] [42P01] ERROR: table "temp_view_sitevisitsass_scores" does not exist
DROP TABLE temp_view_sitevisitsassbiotopes
[2018-02-13 11:59:56] [42P01] ERROR: table "temp_view_sitevisitsassbiotopes" does not exist
DROP TABLE temp_view_sitevisitstreamdimension
[2018-02-13 11:59:56] [42P01] ERROR: table "temp_view_sitevisitstreamdimension" does not exist
DROP TABLE temp_view_sitevisitsubstratum
[2018-02-13 11:59:56] [42P01] ERROR: table "temp_view_sitevisitsubstratum" does not exist
DROP TABLE temp_view_sitevisittaxonxtababundance
[2018-02-13 11:59:56] 0 row(s) affected in 3ms
DROP TABLE temp_view_sitevisittaxonxtababundancesass4
[2018-02-13 11:59:56] 0 row(s) affected in 3ms
DROP TABLE temp_view_sitevisittaxonxtababundancesass5
[2018-02-13 11:59:56] 0 row(s) affected in 3ms
DROP TABLE temp_view_sitevisittaxonxtabscore
[2018-02-13 11:59:56] 0 row(s) affected in 3ms
DROP TABLE temp_view_sitevisittaxonxtabscoresass4
[2018-02-13 11:59:56] 0 row(s) affected in 2ms
DROP TABLE temp_view_sitevisittaxonxtabscoresass5
[2018-02-13 11:59:56] 0 row(s) affected in 4ms
DROP TABLE temp_view_subregion
[2018-02-13 11:59:56] [42P01] ERROR: table "temp_view_subregion" does not exist
DROP TABLE temp_view_summarizedrivermakeup
[2018-02-13 11:59:56] [42P01] ERROR: table "temp_view_summarizedrivermakeup" does not exist
DROP TABLE temp_view_user
[2018-02-13 11:59:56] 0 row(s) affected in 2ms
DROP TABLE assossys
[2018-02-13 11:59:56] [42P01] ERROR: table "assossys" does not exist
ALTER TABLE sitevisitbankmod DROP COLUMN bankmodsid
[2018-02-13 11:59:56] [42P01] ERROR: relation "sitevisitbankmod" does not exist
DROP TABLE bankmods
[2018-02-13 11:59:56] [42P01] ERROR: table "bankmods" does not exist
DROP TABLE channeltype
[2018-02-13 11:59:56] [42P01] ERROR: table "channeltype" does not exist
ALTER TABLE sitechanneltypedetail DROP COLUMN channeltypedetailid
[2018-02-13 11:59:56] [42P01] ERROR: relation "sitechanneltypedetail" does not exist
DROP TABLE channeltypedetail
[2018-02-13 11:59:56] [42P01] ERROR: table "channeltypedetail" does not exist
ALTER TABLE fishcoverpreference DROP COLUMN coverid
[2018-02-13 11:59:56] [42P01] ERROR: relation "fishcoverpreference" does not exist
ALTER TABLE sitevisitfishhabitatcover DROP COLUMN coverid
[2018-02-13 11:59:56] [42P01] ERROR: relation "sitevisitfishhabitatcover" does not exist
DROP TABLE cover
[2018-02-13 11:59:56] [42P01] ERROR: table "cover" does not exist
ALTER TABLE sitevisitfishhabitatcover DROP COLUMN coverestimateid
[2018-02-13 11:59:56] [42P01] ERROR: relation "sitevisitfishhabitatcover" does not exist
DROP TABLE coverestimate
[2018-02-13 11:59:56] [42P01] ERROR: table "coverestimate" does not exist
ALTER TABLE sitevisitcrosssectionpoint DROP COLUMN crosssectionpointid
[2018-02-13 11:59:56] [42P01] ERROR: relation "sitevisitcrosssectionpoint" does not exist
DROP TABLE crosssectionpoint
[2018-02-13 11:59:56] [42P01] ERROR: table "crosssectionpoint" does not exist
DROP TABLE dataintegritycheckexclude
[2018-02-13 11:59:56] [42P01] ERROR: table "dataintegritycheckexclude" does not exist
DROP TABLE embeddedness
[2018-02-13 11:59:56] [42P01] ERROR: table "embeddedness" does not exist
DROP TABLE fishcoverpreference
[2018-02-13 11:59:56] [42P01] ERROR: table "fishcoverpreference" does not exist
ALTER TABLE fishhabitatpreference DROP COLUMN fishhabitatid
[2018-02-13 11:59:56] [42P01] ERROR: relation "fishhabitatpreference" does not exist
ALTER TABLE sitevisitfishhabitatcover DROP COLUMN fishhabitatid
[2018-02-13 11:59:56] [42P01] ERROR: relation "sitevisitfishhabitatcover" does not exist
ALTER TABLE sitevisitfishhabitatsample DROP COLUMN fishhabitatid
[2018-02-13 11:59:56] [42P01] ERROR: relation "sitevisitfishhabitatsample" does not exist
DROP TABLE fishhabitat
[2018-02-13 11:59:56] [42P01] ERROR: table "fishhabitat" does not exist
DROP TABLE fishhabitatpreference
[2018-02-13 11:59:56] [42P01] ERROR: table "fishhabitatpreference" does not exist
DROP TABLE fishintolerance
[2018-02-13 11:59:56] [42P01] ERROR: table "fishintolerance" does not exist
ALTER TABLE sitevisithabitattype DROP COLUMN habitattypeid
[2018-02-13 11:59:56] [42P01] ERROR: relation "sitevisithabitattype" does not exist
DROP TABLE habitattype
[2018-02-13 11:59:56] [42P01] ERROR: table "habitattype" does not exist
DROP TABLE hydrotype
[2018-02-13 11:59:56] [42P01] ERROR: table "hydrotype" does not exist
ALTER TABLE ihisitevisitcatchment DROP COLUMN ihicatchmentid
[2018-02-13 11:59:56] [42P01] ERROR: relation "ihisitevisitcatchment" does not exist
DROP TABLE ihicatchment
[2018-02-13 11:59:56] [42P01] ERROR: table "ihicatchment" does not exist
ALTER TABLE ihisitevisitrivertype DROP COLUMN ihigeomorphzoneid
[2018-02-13 11:59:56] [42P01] ERROR: relation "ihisitevisitrivertype" does not exist
DROP TABLE ihigeomorphzone
[2018-02-13 11:59:56] [42P01] ERROR: table "ihigeomorphzone" does not exist
ALTER TABLE ihisitevisitinstream DROP COLUMN ihiinstreamid
[2018-02-13 11:59:56] [42P01] ERROR: relation "ihisitevisitinstream" does not exist
DROP TABLE ihiinstream
[2018-02-13 11:59:56] [42P01] ERROR: table "ihiinstream" does not exist
ALTER TABLE ihisitevisitinstreamcomponent DROP COLUMN ihiinstreamcomponentid
[2018-02-13 11:59:56] [42P01] ERROR: relation "ihisitevisitinstreamcomponent" does not exist
DROP TABLE ihiinstreamcomponent
[2018-02-13 11:59:56] [42P01] ERROR: table "ihiinstreamcomponent" does not exist
ALTER TABLE ihisitevisitriparianzone DROP COLUMN ihiriparianzoneid
[2018-02-13 11:59:56] [42703] ERROR: column "ihiriparianzoneid" of relation "ihisitevisitriparianzone" does not exist
DROP TABLE ihiriparianzone
[2018-02-13 11:59:56] [42P01] ERROR: table "ihiriparianzone" does not exist
ALTER TABLE ihisitevisitriparianzonecomponent DROP COLUMN ihiriparianzonecomponentid
[2018-02-13 11:59:56] [42703] ERROR: column "ihiriparianzonecomponentid" of relation "ihisitevisitriparianzonecomponent" does not exist
DROP TABLE ihiriparianzonecomponent
[2018-02-13 11:59:56] [42P01] ERROR: table "ihiriparianzonecomponent" does not exist
ALTER TABLE ihisitevisitseasonality DROP COLUMN ihiseasonalityid
[2018-02-13 11:59:56] [42P01] ERROR: relation "ihisitevisitseasonality" does not exist
DROP TABLE ihiseasonality
[2018-02-13 11:59:56] [42P01] ERROR: table "ihiseasonality" does not exist
DROP TABLE ihisitevisitcatchment
[2018-02-13 11:59:56] [42P01] ERROR: table "ihisitevisitcatchment" does not exist
DROP TABLE ihisitevisitinstream
[2018-02-13 11:59:56] [42P01] ERROR: table "ihisitevisitinstream" does not exist
DROP TABLE ihisitevisitinstreamcomponent
[2018-02-13 11:59:56] [42P01] ERROR: table "ihisitevisitinstreamcomponent" does not exist
DROP TABLE ihisitevisitrivertype
[2018-02-13 11:59:56] [42P01] ERROR: table "ihisitevisitrivertype" does not exist
DROP TABLE ihisitevisitseasonality
[2018-02-13 11:59:56] [42P01] ERROR: table "ihisitevisitseasonality" does not exist
DROP TABLE ihiwidth
[2018-02-13 11:59:56] [42P01] ERROR: table "ihiwidth" does not exist
DROP TABLE landuse
[2018-02-13 11:59:56] [42P01] ERROR: table "landuse" does not exist
ALTER TABLE sitevisitformulacriterionentry DROP COLUMN levelofconfidenceid
[2018-02-13 11:59:56] [42P01] ERROR: relation "sitevisitformulacriterionentry" does not exist
DROP TABLE levelofconfidence
[2018-02-13 11:59:56] [42P01] ERROR: table "levelofconfidence" does not exist
ALTER TABLE sitevisitripvegchannelimpact DROP COLUMN ripvegimpactid
[2018-02-13 11:59:56] [42P01] ERROR: relation "sitevisitripvegchannelimpact" does not exist
DROP TABLE Ripvegimpact
[2018-02-13 11:59:56] [42P01] ERROR: table "ripvegimpact" does not exist
ALTER TABLE sitevisit DROP COLUMN biotope
[2018-02-13 11:59:56] [42703] ERROR: column "biotope" of relation "sitevisit" does not exist
DROP TABLE rivermakeup
[2018-02-13 11:59:56] [42P01] ERROR: table "rivermakeup" does not exist
ALTER TABLE fishhabitatsamplingcatchability DROP COLUMN samplingmethodid
[2018-02-13 11:59:56] [42P01] ERROR: relation "fishhabitatsamplingcatchability" does not exist
ALTER TABLE sitevisitfishhabitatsample DROP COLUMN samplingmethodid
[2018-02-13 11:59:56] [42P01] ERROR: relation "sitevisitfishhabitatsample" does not exist
DROP TABLE Samplingmethod
[2018-02-13 11:59:56] [42P01] ERROR: table "samplingmethod" does not exist
DROP TABLE Sassbiotopespecificbiotope
[2018-02-13 11:59:56] [42P01] ERROR: table "sassbiotopespecificbiotope" does not exist
DROP TABLE Sitechanneltypedetail
[2018-02-13 11:59:56] [42P01] ERROR: table "sitechanneltypedetail" does not exist
DROP TABLE Sitetransaction
[2018-02-13 11:59:56] [42P01] ERROR: table "sitetransaction" does not exist
DROP TABLE Traceriver
[2018-02-13 11:59:56] [42P01] ERROR: table "traceriver" does not exist

[2018-02-13 11:59:56] Summary: 172 of 172 statements executed in 563ms (7402 symbols in file)

```

**Comment by sonlinux** [comment]
@timlinux did you ran it on a fresh restore of the database which has about 218 tables?
That error is because the tables and or columns specified are already deleted.

**Comment by timlinux** [comment]
@sonlinux 

Please share a link to the original db dump and I will test it. Thanks!

**Comment by timlinux** [comment]
OK thank you @sonlinux I have tested the script against the full database and it works cleanly. Good job!

**Comment by sonlinux** [comment]
Thanks @timlinux

**Pull request merged**
